# Generated by Django 4.2.5 on 2024-03-26 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoq', '0004_alter_producto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_caducidad',
        ),
        migrations.AddField(
            model_name='stock',
            name='fecha_caducidad',
            field=models.DateField(default=datetime.date(2000, 2, 8)),
        ),
    ]
