# Generated by Django 4.2.5 on 2024-04-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoq', '0005_remove_producto_fecha_caducidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='latitud',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='longitud',
            field=models.FloatField(default=0.0),
        ),
    ]
