# Generated by Django 4.2.5 on 2024-04-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoq', '0006_cliente_direccion_alter_cliente_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoventa',
            name='direccion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='puntoventa',
            name='latitud',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='puntoventa',
            name='longitud',
            field=models.FloatField(default=0.0),
        ),
    ]
