# Generated by Django 4.2.5 on 2024-04-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoq', '0007_puntoventa_direccion_alter_puntoventa_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
