# Generated by Django 4.2.5 on 2024-04-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stoq', '0008_detalleventa_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='stoq.venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
